const translations={
  'nav.work':'PROYECTOS','nav.about':'SOBRE MÍ','nav.contact':'CONTACTO','nav.label':'Navegación principal','nav.open':'Abrir menú','nav.close':'Cerrar menú','language.switch':'Cambiar a inglés',
  'general.role':'GUIONISTA · DIRECTOR','general.roleTitle':'Guionista · Director','general.viewProject':'VER PROYECTO →','general.aboutLink':'SOBRE MÍ →','general.contactLink':'CONTACTO →','general.signature':'Guionista · Director<br>Barcelona, España',
  'home.hero.statement':'Largometrajes de thriller, drama y fantasía construidos desde el personaje y el conflicto.','home.work.label':'PROYECTOS DESTACADOS','home.about.preview':'Javier L. Teso es guionista y director de Barcelona. Desarrolla largometrajes de thriller, drama, fantasía y aventura construidos desde el personaje, el conflicto y las decisiones difíciles.','home.recognition.label':'RECONOCIMIENTOS DESTACADOS',
  'title.verdugo':'LA HABITACIÓN<br>DEL VERDUGO','title.verdugoPlain':'LA HABITACIÓN DEL VERDUGO','title.volver':'VOLVER A<br>ARRANCAR',
  'genre.verdugo':'Thriller psicológico · Largometraje','genre.volver':'Dramedia familiar · Largometraje','genre.genpets':'Aventura familiar de ciencia ficción · Largometraje',
  'tagline.verdugo':'Siete condenados. Solo uno sobrevivirá.','tagline.volver':'Reparando una moto. Restaurando el pasado.','tagline.genpets':'Fueron diseñados para amarte... y para matarte.',
  'award.bestScreenplay':'Mejor guion · 2026','award.bestOriginal':'Mejor guion original · 2026','award.bestFantasy':'Mejor guion de fantasía · 2026',
  'contact.heading':'HABLEMOS','contact.headingPlain':'HABLEMOS','contact.intro':'Para consultas de producción, representación, colaboraciones o solicitudes de guion, puedes ponerte en contacto conmigo.','contact.name':'NOMBRE','contact.email':'EMAIL','contact.company':'EMPRESA / ORGANIZACIÓN','contact.optional':'(OPCIONAL)','contact.reason':'MOTIVO DEL CONTACTO','contact.reason.placeholder':'SELECCIONA UN MOTIVO','contact.reason.production':'Consulta de producción','contact.reason.representation':'Representación','contact.reason.collaboration':'Colaboración','contact.reason.materials':'Solicitud de guion / pitch deck','contact.reason.other':'Otra consulta profesional','contact.project':'PROYECTO','contact.project.placeholder':'NINGÚN PROYECTO CONCRETO','contact.project.verdugo':'La habitación del verdugo','contact.project.volver':'Volver a arrancar','contact.message':'MENSAJE','contact.filter':'Aviso: este formulario no está destinado a servicios de distribución, marketing, promoción, inscripción en festivales o publicidad de pago.','contact.submit':'ENVIAR MENSAJE →','contact.sending':'ENVIANDO…','contact.success':'MENSAJE ENVIADO.','contact.successDetail':'Gracias por ponerte en contacto. Te responderé lo antes posible.','contact.error':'Ha ocurrido un error. Inténtalo de nuevo.','contact.required':'Este campo es obligatorio.','contact.invalidEmail':'Introduce una dirección de correo válida.',
  'section.logline':'LOGLINE','section.story':'LA HISTORIA','section.vision':'VISIÓN DEL DIRECTOR','section.images':'IMÁGENES SELECCIONADAS','section.posterConcept':'PÓSTER CONCEPTUAL','section.recognition':'RECONOCIMIENTOS','section.status':'ESTADO DEL PROYECTO','section.materials':'MATERIALES','section.characters':'PERSONAJES',
  'poster.open':'Ampliar póster conceptual','poster.close':'Cerrar póster conceptual',
  'materials.available':'Guion y pitch deck disponibles bajo petición.','materials.request':'SOLICITAR MATERIALES →',
  'verdugo.logline':'Después de perderlo todo en un divorcio devastador, Víctor vive al borde del suicidio en un decadente motel de carretera. Una noche, una misteriosa llamada lo obliga a juzgar a siete desconocidos acusados de haber escapado a la justicia: solo puede salvar a uno y, si abandona la habitación, morirán todos.',
  'verdugo.rules.heading':'LAS DOS REGLAS','verdugo.rule1':'SALVA A UNO.<br>LOS DEMÁS MUEREN.','verdugo.rule2':'SAL DE LA HABITACIÓN.<br>MUEREN TODOS.',
  'verdugo.story1':'Víctor despierta en la habitación del motel al sonido del teléfono. Una voz serena asegura que siete personas están retenidas al otro lado de la pared, acusadas de actos terribles que quedaron impunes. Víctor no tiene forma de saber si lo que escucha es cierto.','verdugo.story2':'Debe oírlas una a una y decidir, contrarreloj, quién merece vivir. Solo puede salvar a una. No puede abandonar la habitación. Y cada decisión lo acerca a una última voz que conoce demasiado bien.',
  'verdugo.vision1':'Un thriller psicológico contenido y en tiempo real, construido sobre la interpretación, el sonido y una presión moral irreversible. La violencia permanece casi siempre fuera de campo: el suspense nace de llamadas distorsionadas, gritos amortiguados, golpes, silencios y de aquello que el espectador imagina al otro lado de la pared.','verdugo.vision2':'La habitación se convierte progresivamente en un paisaje mental de culpa, justicia y duelo. Una paleta de ocres desaturados, azules oxidados y sombras cada vez más densas acompaña el derrumbe de Víctor mientras la cámara permanece cerca, atrapada con él.','verdugo.status':'Guion de largometraje completo y registrado. En búsqueda de productora y socios de coproducción para desarrollar el proyecto con Javier L. Teso como guionista y director.',
  'volver.logline':'Cuando la muerte de su padre lo obliga a regresar al pueblo del que huyó más de veinte años atrás, un prestigioso chef deberá convivir con el hermano que nunca le perdonó su abandono. Mientras intenta restaurar la vieja moto familiar, ambos deberán enfrentarse a las heridas que los separaron antes de poder volver a arrancar.',
  'volver.story1':'Tras más de veinte años lejos de casa, Toño, un prestigioso chef que vive en Francia, regresa al pueblo para asistir al funeral de su padre. Allí lo espera Felipe, el hermano que se quedó junto a la familia y que nunca le perdonó que desapareciera sin dar explicaciones.','volver.story2':'En el corral permanece la vieja Montesa Impala 2 de su padre. Movido por la culpa y los recuerdos, Toño decide restaurarla pese a no saber casi nada de mecánica. Felipe observa el intento con una mezcla de burla y resentimiento: para él, arreglar la moto no compensa veintidós años de ausencia.','volver.story3':'Elena, la hija de trece años de Felipe, se convierte en un puente inesperado entre ambos. A medida que la moto vuelve a cobrar vida, también lo hace la historia que los hermanos llevan años evitando.',
  'volver.impala.heading':'LA IMPALA. LA RESTAURACIÓN.','volver.impala.lead':'Una moto detenida. Una historia familiar esperando volver a arrancar.','volver.impala.body':'La Montesa Impala 2 es una tarea concreta y también la medida emocional del regreso de Toño. Cada pieza que consigue recuperar acerca el pasado, sin prometer que todo lo roto pueda restaurarse.',
  'volver.character.tono':'40 años. Prestigioso chef, perfeccionista y acostumbrado a tenerlo todo bajo control. Regresa al pueblo que abandonó a los dieciocho años y a una familia que ha mantenido a distancia.','volver.character.felipe':'38 años. El hermano que se quedó. Responsable, familiar y profundamente arraigado al pueblo; convirtió la ausencia de Toño en un resentimiento que nunca ha sabido expresar.','volver.character.elena':'13 años. Curiosa, directa y poco dispuesta a aceptar los silencios de los adultos. Se convierte en el puente inesperado entre los hermanos.','volver.character.impalaName':'LA IMPALA','volver.character.impala':'La Montesa Impala 2 de su padre. Una presencia física cargada de recuerdos, silencios y una historia familiar que lleva décadas detenida.',
  'volver.vision1':'Una dramedia familiar íntima y contenida, donde el humor nace de los personajes, las pullas y la incomodidad de volver a compartir espacio. Piedra, polvo, ocres desgastados y luz de última hora de la tarde dan al entorno rural la calidez imperfecta de los lugares ligados a la memoria.','volver.vision2':'Al principio, la cámara mantendrá a Toño y Felipe separados mediante puertas, muebles o distintas profundidades dentro del plano. Poco a poco comenzarán a compartir el mismo encuadre. La restauración se filma desde lo físico —grasa, metal, tornillos que se resisten e intentos fallidos— sin convertir la moto en una metáfora obvia ni en un atajo hacia la reconciliación.','volver.status':'Proyecto en desarrollo avanzado. Guion de largometraje completo y registrado. En búsqueda de una productora que acompañe su desarrollo con Javier L. Teso como guionista y director.',
  'genpets.logline':'Cuatro amigos descubren en una mina abandonada un laboratorio secreto donde una organización crea mascotas genéticamente modificadas. Cuando los Genpets escapan, deberán sobrevivir a las criaturas y evitar que lleguen al mundo exterior.',
  'genpets.story1':'Steve, Ellen, Geek y Gallina empiezan el verano en su tranquilo pueblo sabiendo que quizá sea el último que pasen juntos antes de ir a institutos diferentes. Los rumores sobre una mina abandonada los llevan hasta BioGen, un laboratorio clandestino que combina ADN de distintas especies para fabricar mascotas personalizadas.','genpets.story2':'Una sola gota de sangre de Steve activa uno de los especímenes: Cuddles, el primer Genpet viable. Pero cuando otras criaturas escapan, el descubrimiento se convierte en una lucha por sobrevivir, encontrar una salida y evitar que los experimentos alcancen el mundo exterior.','genpets.story3':'Con la ayuda de la Dra. Astoria, una científica horrorizada por el proyecto que ayudó a crear, los cuatro amigos deberán enfrentarse a BioGen, a sus criaturas y al miedo de que aquel último verano juntos pueda ser realmente el último.',
  'genpets.facts.heading':'LOS GENPETS','genpets.fact1':'127 ESPECIES.','genpets.fact2':'UNA GOTA DE TU SANGRE.','genpets.fact3':'UNA CRIATURA CREADA PARA TI.','genpets.crew.heading':'LA PANDILLA',
  'genpets.character.steve':'12 años. El más intrépido del grupo. Su curiosidad por la mina lo convierte en el motor de la aventura.','genpets.character.ellen':'12 años. Determinada y aventurera. Aunque se ha distanciado del grupo, la aventura demuestra que el vínculo con sus amigos sigue intacto.','genpets.character.geek':'12 años. El cerebro creativo de la pandilla: inventor, tecnológico y siempre buscando una salida.','genpets.character.gallina':'11 años. El más miedoso y torpe del grupo. Cuando llega el momento, descubre un valor que ni él sabía que tenía.',
  'genpets.vision1':'Una aventura juvenil contemporánea que recupera la amistad, el peligro y el sentido del asombro del gran cine de aventuras de los años 80 y 90 sin convertirse en una imitación nostálgica. En el exterior, el verano y el pequeño pueblo respiran con luz cálida y planos abiertos; al descender a la mina, los encuadres se cierran y el espacio se vuelve claustrofóbico. El laboratorio introduce un mundo frío, fluorescente y deliberadamente antinatural.','genpets.vision2':'En el centro está Cuddles: una criatura creada como producto que acaba definida por su vínculo con Steve. Esa relación da a la película su corazón emocional y contrapone la inocencia de los niños a un mundo adulto dispuesto a convertir la propia vida en mercancía.','genpets.status':'Guion de largometraje completo y registrado. En búsqueda de productora y socios estratégicos para continuar el desarrollo del proyecto.',
  'about.bio':'<p>Javier L. Teso (Barcelona, 1980) es guionista y director. Desde 2011 compagina su trayectoria en el ámbito educativo con la escritura de guion y la realización audiovisual.</p><p>Sus primeras piezas, <em>Noche Zombie</em> y <em>Hombre Lobo</em>, fueron creadas para las proyecciones de Halloween de Phenomena Experience. Posteriormente dirigió los cortometrajes <em>228</em> (2013) y <em>Natural Born Directors</em> (2015), este último realizado con el apoyo del Ayuntamiento de Sant Boi de Llobregat.</p><p>Como guionista desarrolla proyectos de largometraje en géneros como el thriller, la dramedia, el terror y la fantasía. Entre sus trabajos actuales se encuentran <em>La habitación del verdugo</em>, <em>Volver a arrancar</em> y <em>Genpets</em>.</p><p>Sus guiones han recibido distintos reconocimientos internacionales: <em>La habitación del verdugo</em> obtuvo los premios a Mejor Guion en Liberty Films Festival y Mejor Guion Original en Your Way International Film Festival; <em>Genpets</em> fue reconocido como Mejor Guion en Cinemabriz y Mejor Guion de Fantasía en Los Angeles Film &amp; Documentary Awards.</p><p>Actualmente busca productoras, representación y colaboradores con los que continuar desarrollando sus proyectos de largometraje.</p><p class="meta">Barcelona, España</p>',
  'alt.verdugo.home':'Víctor está sentado de espaldas en la cama del motel junto al teléfono.','alt.volver.home':'Toño repara la Montesa en el corral familiar mientras Felipe observa desde el fondo.','alt.genpets.home':'Cuatro amigos dejan sus bicicletas frente a una mina abandonada.',
  'alt.verdugo.hero':'Víctor escucha con miedo a través de la pared del motel.','alt.verdugo.phone':'Un teléfono espera sobre la mesita de noche de la habitación de Víctor.','alt.verdugo.bottle':'Una botella vacía yace junto a un espejo roto en el suelo del motel.','alt.verdugo.door':'Víctor agarra el pomo de la habitación del motel y duda antes de abrir la puerta.',
  'alt.volver.hero':'Toño y Felipe contemplan el valle al atardecer junto a la Montesa Impala 2.','alt.volver.repair':'Unas manos manchadas de grasa trabajan en el motor de la Montesa Impala 2.','alt.volver.elena':'Toño habla con Elena en una zona de picnic rural.','alt.volver.room':'El comedor habitado de la casa rural de la familia.',
  'alt.genpets.hero':'El laboratorio secreto de BioGen visto a través de una rejilla metálica.','alt.genpets.criocuna':'Un embrión de Genpet reposa dentro de una bolsa transparente llena de líquido ámbar en la criocuna del laboratorio.','alt.genpets.cuddles':'Steve se arrodilla frente a Cuddles en el laboratorio.','alt.genpets.threat':'Steve y Cuddles se esconden de los Genpets fugados en el oscuro laboratorio.','alt.about.profile':'Retrato del guionista y director Javier L. Teso.'
};

const metadata={
  home:{en:{title:'Javier L. Teso — Screenwriter & Director',description:'Official portfolio of Barcelona-based screenwriter and director Javier L. Teso. Feature films across thriller, drama, fantasy and adventure.',ogTitle:'Javier L. Teso — Screenwriter & Director',ogDescription:'Character-driven feature films across thriller, drama and fantasy.'},es:{title:'Javier L. Teso — Guionista y director',description:'Portfolio oficial del guionista y director Javier L. Teso. Largometrajes de thriller, drama, fantasía y aventura.',ogTitle:'Javier L. Teso — Guionista y director',ogDescription:'Largometrajes construidos desde el personaje y el conflicto.'}},
  about:{en:{title:'About — Javier L. Teso',description:'About Barcelona-based screenwriter and director Javier L. Teso.',ogTitle:'About — Javier L. Teso',ogDescription:'Screenwriter and director developing character-driven feature films.'},es:{title:'Sobre mí — Javier L. Teso',description:'Trayectoria del guionista y director barcelonés Javier L. Teso.',ogTitle:'Sobre mí — Javier L. Teso',ogDescription:'Guionista y director de largometrajes de thriller, drama, fantasía y aventura.'}},
  contact:{en:{title:'Contact — Javier L. Teso',description:'Contact screenwriter and director Javier L. Teso for production, representation and collaborations.',ogTitle:'Contact — Javier L. Teso',ogDescription:'Production enquiries, representation, collaborations and screenplay requests.'},es:{title:'Contacto — Javier L. Teso',description:'Contacto profesional con el guionista y director Javier L. Teso.',ogTitle:'Contacto — Javier L. Teso',ogDescription:'Consultas de producción, representación, colaboraciones y solicitudes de guion.'}},
  verdugo:{en:{title:"The Executioner's Room — Javier L. Teso",description:"The Executioner's Room is a real-time psychological thriller feature screenplay by Javier L. Teso.",ogTitle:"The Executioner's Room",ogDescription:'Seven condemned. Only one will survive.'},es:{title:'La habitación del verdugo — Javier L. Teso',description:'La habitación del verdugo es un thriller psicológico en tiempo real escrito por Javier L. Teso.',ogTitle:'La habitación del verdugo',ogDescription:'Siete condenados. Solo uno sobrevivirá.'}},
  volver:{en:{title:'Back in Gear — Javier L. Teso',description:'Back in Gear is a family dramedy feature screenplay about two brothers and a Montesa Impala 2.',ogTitle:'Back in Gear',ogDescription:'Repairing a motorcycle. Restoring the past.'},es:{title:'Volver a arrancar — Javier L. Teso',description:'Volver a arrancar es una dramedia familiar sobre dos hermanos y una Montesa Impala 2.',ogTitle:'Volver a arrancar',ogDescription:'Reparando una moto. Restaurando el pasado.'}},
  genpets:{en:{title:'Genpets — Javier L. Teso',description:'Genpets is a family science-fiction adventure feature screenplay by Javier L. Teso.',ogTitle:'Genpets',ogDescription:'Designed to love you... and to kill you.'},es:{title:'Genpets — Javier L. Teso',description:'Genpets es un largometraje de aventura familiar y ciencia ficción escrito por Javier L. Teso.',ogTitle:'Genpets',ogDescription:'Fueron diseñados para amarte... y para matarte.'}}
};

const originals=new WeakMap();
document.querySelectorAll('[data-i18n],[data-i18n-html],[data-i18n-alt],[data-i18n-aria]').forEach(el=>originals.set(el,{text:el.textContent,html:el.innerHTML,alt:el.getAttribute('alt'),aria:el.getAttribute('aria-label')}));

function setMeta(selector,value){const el=document.querySelector(selector);if(el)el.setAttribute('content',value)}
function setLanguage(lang){
  const spanish=lang==='es';
  document.documentElement.lang=lang;
  document.querySelectorAll('[data-i18n]').forEach(el=>{const o=originals.get(el);el.textContent=spanish?translations[el.dataset.i18n]:o.text});
  document.querySelectorAll('[data-i18n-html]').forEach(el=>{const o=originals.get(el);el.innerHTML=spanish?translations[el.dataset.i18nHtml]:o.html});
  document.querySelectorAll('[data-i18n-alt]').forEach(el=>{const o=originals.get(el);el.alt=spanish?translations[el.dataset.i18nAlt]:o.alt});
  document.querySelectorAll('[data-i18n-aria]').forEach(el=>{const o=originals.get(el);el.setAttribute('aria-label',spanish?translations[el.dataset.i18nAria]:o.aria)});
  document.querySelectorAll('[data-poster-en][data-poster-es]').forEach(img=>{
    img.src=spanish?img.dataset.posterEs:img.dataset.posterEn;
    img.alt=spanish?img.dataset.altEs:img.dataset.altEn;
  });
  const page=document.body.dataset.page,m=metadata[page]?.[lang];if(m){document.title=m.title;setMeta('meta[name="description"]',m.description);setMeta('meta[property="og:title"]',m.ogTitle);setMeta('meta[property="og:description"]',m.ogDescription)}
  let locale=document.querySelector('meta[property="og:locale"]');if(!locale){locale=document.createElement('meta');locale.setAttribute('property','og:locale');document.head.append(locale)}locale.content=spanish?'es_ES':'en_GB';
  try{localStorage.setItem('jlt-language-v2',lang)}catch(e){}
}

let language='es';try{const savedLanguage=localStorage.getItem('jlt-language-v2');language=savedLanguage==='en'||savedLanguage==='es'?savedLanguage:'es'}catch(e){}setLanguage(language);
const header=document.querySelector('.site-header'),menu=document.querySelector('.menu-button'),links=document.querySelector('.nav-links');
function updateHeader(){header?.classList.toggle('scrolled',scrollY>24)}updateHeader();addEventListener('scroll',updateHeader,{passive:true});
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true',next=!open;menu.setAttribute('aria-expanded',String(next));menu.setAttribute('aria-label',next?(document.documentElement.lang==='es'?translations['nav.close']:'Close menu'):(document.documentElement.lang==='es'?translations['nav.open']:'Open menu'));links?.classList.toggle('open',next);header?.classList.toggle('menu-open',next)});
links?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu?.setAttribute('aria-expanded','false');links.classList.remove('open');header?.classList.remove('menu-open')}));
document.querySelector('.language-toggle')?.addEventListener('click',()=>setLanguage(document.documentElement.lang==='es'?'en':'es'));
const io=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');io.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));

document.querySelectorAll('.poster-concept-frame').forEach(frame=>{
  const trigger=frame.querySelector('.poster-open'),poster=trigger?.querySelector('img'),dialog=frame.querySelector('.poster-dialog'),expanded=dialog?.querySelector('.poster-expanded'),close=dialog?.querySelector('.poster-close');
  trigger?.addEventListener('click',()=>{expanded.src=poster.src;expanded.alt=poster.alt;dialog.showModal()});
  close?.addEventListener('click',()=>dialog.close());
  dialog?.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});
});

const contactForm=document.querySelector('#contact-form');
if(contactForm){
  const submitButton=contactForm.querySelector('.form-submit'),status=document.querySelector('#form-status'),startedAt=Date.now();
  const query=new URLSearchParams(location.search),reason=query.get('reason'),project=query.get('project');
  if(reason==='materials')contactForm.elements.reason.value='Screenplay / pitch deck request';
  if(['The Executioner\'s Room','Back in Gear','Genpets'].includes(project))contactForm.elements.project.value=project;
  const showError=(name,message)=>{const output=contactForm.querySelector(`[data-error-for="${name}"]`),field=contactForm.elements[name];if(output)output.textContent=message;if(field)field.setAttribute('aria-invalid','true')};
  const clearErrors=()=>{contactForm.querySelectorAll('.field-error').forEach(el=>el.textContent='');contactForm.querySelectorAll('[aria-invalid="true"]').forEach(el=>el.removeAttribute('aria-invalid'));status.hidden=true;status.className='form-status'};
  contactForm.addEventListener('submit',async event=>{
    event.preventDefault();clearErrors();
    const isSpanish=document.documentElement.lang==='es',required=isSpanish?translations['contact.required']:'This field is required.',invalidEmail=isSpanish?translations['contact.invalidEmail']:'Enter a valid email address.';
    let valid=true;['name','email','reason','message'].forEach(name=>{if(!contactForm.elements[name].value.trim()){showError(name,required);valid=false}});
    if(contactForm.elements.email.value&&!contactForm.elements.email.validity.valid){showError('email',invalidEmail);valid=false}
    if(!valid){contactForm.querySelector('[aria-invalid="true"]')?.focus();return}
    if(contactForm.elements._gotcha.value||Date.now()-startedAt<2500)return;
    submitButton.disabled=true;submitButton.textContent=isSpanish?translations['contact.sending']:'SENDING…';
    try{const response=await fetch(contactForm.action,{method:'POST',body:new FormData(contactForm),headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Formspree submission failed');contactForm.reset();status.hidden=false;status.classList.add('success');status.innerHTML=`<strong>${isSpanish?translations['contact.success']:'MESSAGE SENT.'}</strong><span>${isSpanish?translations['contact.successDetail']:"Thanks for getting in touch. I'll get back to you as soon as possible."}</span>`;submitButton.hidden=true}
    catch(error){status.hidden=false;status.classList.add('error');status.textContent=isSpanish?translations['contact.error']:'Something went wrong. Please try again.';submitButton.disabled=false;submitButton.textContent=isSpanish?translations['contact.submit']:'SEND MESSAGE →'}
  });
}
